world = (
    (#0
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                   EE D",
        "D R                                 EE D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#1
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                   EE D",
        "D R                                 EE D",
        "DGGGGGGGGGLLLLLLLLLLLLLLLLLLLLGGGGGGGGGD",
    ),
    (#2
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                         EE D",
        "D                                         EE D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "D                                            D",
        "DR                                           D",
        "DGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLGGD",
    ),
    (#3
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                         DD           D",
        "D                         DD           D",
        "D                         DD           D",
        "D                         DD           D",
        "D                         DD           D",
        "D                         DD           D",
        "D                         DD        EE D",
        "D                         DD        EE D",
        "D                         DD           D",
        "D              GGGGGG     DD    GGGGGGGD",
        "D              DDDDDD     DD     DDDDDDD",
        "D              DDDDDD     DD           D",
        "D           GGGDDDDDD                  D",
        "D            DDDDDDDD                  D",
        "D              DDDDDD                  D",
        "D              DDDDDD                  D",
        "D              DDDDDD                  D",
        "D R            DDDDDD                  D",
        "DGGGGGGGGGGGGGGDDDDDDLLLLTTTTLLLLLLLLLLD",
    ),
    (#4
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D R                                    D",
        "DGGGGGGGGG         GGGGGGGGGGGGGGGGGGGGD",
        "DDDDDDDDDD                             D",
        "DDDDDDDDDD                        G    D",
        "DDDDDDDDDD                        D    D",
        "DDDDDDDDDD                        D EE D",
        "DDDDDDDDDD                        D EE D",
        "DDDDDDDDDD                        D    D",
        "DDDDDDDDDD                        DGGGGD",
        "DDDDDDDDDD                        DDDDDD",
        "DDDDDDDDDDLLLLLLLLLLLLLLLTTTTLLLLLDDDDDD",
    ),
    (#5
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                           EE D",
        "D                                                           EE D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "D                                                              D",
        "DR                                                             D",
        "DGGLLLLLLLLLLTTLLLLLLLLLLTTLLLLLLLLLLTTLLLLLLLLLLTTLLLLLLLLLLGGD",
    ),
    (#6
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D R                                    D",
        "DGGGGGGGGGGGGGGGGG    GGGGGGGGGGGGGGGGGD",
        "DDDDDDDDDDDDDDDDDD    DDDDDDDDDDDDDDDDDD",
        "DDDDDDDDDDDDDDDDDD    DDDDD         DDDD",
        "DDDDDDDDDDDDDDDDDD    DDDDD         DDDD",
        "DDDDDDDDDDDDDDDDDD            DDDD  DDDD",
        "DDDDDDDDDDDDDDDDDD            DDD    DDD",
        "DDDDDDDDDDDDDDDDDD            DDD EE DDD",
        "DDDDDDDDDDDDDDDDDD    LLLLL   DDD EE DDD",
        "DDDDDDDDDDDDDDDDDD    DDDDDTTTDDD    DDD",
        "DDDDDDDDDDDDDDDDDDLLLLDDDDDDDDDDDDDDDDDD",
    ),
    (#7
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D EE                                   D",
        "D EE                                   D",
        "DGGGGGGGGGGGGGG                        D",
        "D            DD                        D",
        "D            DD                        D",
        "D            DD                        D",
        "D            DD                        D",
        "D R          DD                        D",
        "DGGGGG       DD                        D",
        "DDDDDD       DD                        D",
        "DDDDDD       DD                        D",
        "DDDDDD       DD                        D",
        "DDDDDD       DD       GGGGGGGGGGGGGGGGGD",
        "DDDDDD       DD       DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDD                DDDDDDDDDDDDDDDDDD",
        "DDDDDDTTTTTTTTTTTTTTTTDDDDDDDDDDDDDDDDDD",
    ),
    (#8
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D               GG                     D",
        "D               DD                     D",
        "D               DD                     D",
        "D               DD                     D",
        "D               DDGGGG                 D",
        "t               DDDDD                  D",
        "t               DDD                    D",
        "t               DD                     D",
        "D               DD                     D",
        "D               DD                     D",
        "D               DD                  EE D",
        "D R             DD                  EE D",
        "DGGGGGGGGGGGGGGGDDGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#9
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "t                                      D",
        "t R                                    t",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGG          t",
        "D                                      t",
        "D                                      t",
        "D                                      t",
        "t                                      t",
        "t          GGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
        "t                                      D",
        "t                                      D",
        "t                                      D",
        "t                                      t",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGG           t",
        "D                                      t",
        "D                                      t",
        "D                                      t",
        "t                                      t",
        "t           GGGGGGGGGGGGGGGGGGGGGGGGGGGD",
        "t                                      D",
        "t                                      D",
        "t                                      D",
        "t                                      t",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGG           t",
        "D                                      t",
        "D  EE                                  t",
        "D  EE                                  t",
        "D                                      t",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#10
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "t           D           D           D    D",
        "t           D           D           D EE D",
        "t           D           D           D EE D",
        "t           D           D           D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     t     D    D",
        "t     t     D     t     D     t     D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     D     D    D",
        "t     t     D     t     D     D     t    D",
        "t     t     D     t     D     D     t    D",
        "t     t           t           t          D",
        "t     t           t           t          D",
        "t     t           t           t          D",
        "t  R  t           t           t          D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#11
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "D                                                                           EE D",
        "D                                                                           EE D",
        "D                                                                              D",
        "D                                                                              D",
        "t                                                                              D",
        "t                                                                              D",
        "t                                                                              D",
        "t                                                                              D",
        "D                                                                              D",
        "D                                                                              D",
        "DR                                                                             D",
        "DGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLGGD",
    ),
    (#12
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                   EE D",
        "D                                   EE D",
        "D                                      D",
        "D                             GGGGGGGGGD",
        "D                              DDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D R                B                   D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#13
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                                   EE D",
        "D                                   EE D",
        "D                                      D",
        "DGGGGGGGGGGG                GGGGGGGGGGGD",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D        R         B                   D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#14
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                             D",
        "D                                             D",
        "t                                          EE D",
        "t                                          EE D",
        "t                       TTTTT                 D",
        "D                       DDDDD                 D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D  B     R                                    D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#15
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                   EE D",
        "D                                   EE D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                       B              D",
        "D                       G              D",
        "D                                      D",
        "D            B                         D",
        "D            G                         D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D R    B                               D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#16
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                        D             D",
        "D                        D     EE      D",
        "D                        D     EE      D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                        D             D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D R   B                                D",
        "DGGGGGGGGGGGGGGGGGGGGGGGTTTGGGGGGGGGGGGD",
    ),
    (#17
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D EE                                   D",
        "D EE                                   D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "D                            B         D",
        "D                            G         D",
        "D                                      D",
        "D                                      D",
        "D                                      D",
        "t                                      D",
        "t                                      D",
        "t                                      D",
        "t                                      D",
        "D                                      D",
        "D                                      D",
        "D R                                    D",
        "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#18
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D           GG                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                         D",
        "D           DD                      EE D",
        "D           DD                      EE D",
        "D R         DD                         D",
        "DGGGGGGGGTTGDDGGGGGGGGGGGGGGGGGGGGGGGGGD",
    ),
    (#19
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                 D                    D",
        "D                 D                    D",
        "D          GG     D                    D",
        "D          DD     D                    D",
        "D          DD     D                    D",
        "D          DD     D              G     D",
        "D          DD     D              D     D",
        "D          DD     D              D     D",
        "D          DD     D              D     D",
        "D          DD     D              D     D",
        "D          DD                    D     D",
        "D          DD                    D     D",
        "D          DD                    D     D",
        "D          tt                    D     D",
        "D          tt                    D     D",
        "D          DD                    D  EE D",
        "D          DD                    D  EE D",
        "D R        DD                    D     D",
        "DGGGGGGGGGGDDLLLLLLLLLLLLLLLLLLLLDLGGGGD",
    ),
    (#20
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                   EE D",
        "D                                                                                                                                   EE D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "t                                                                                                                                      D",
        "t                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "DR                                                                                                                                     D",
        "DGGLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLTTLLLLLLLLLLLLLLLLLLLLLLLLLLGGD",
    ),
    (#21
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DR                                 D          D",
        "DGG                                D       EE D",
        "D                                  D       EE D",
        "D                                  D          D",
        "D                                  D    GGGGGGD",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                                             D",
        "D                    B                        D",
        "D                    G                        D",
        "DLLLLLLLLLLLLLLLLLLLLDLLLLLLLLLLLLLLLLLLLLLLLLD",
    ),
    (#22
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                  GG                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  tD                  D",
        "D                  tD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD               EE D",
        "D R                DD               EE D",
        "DGGGGGGGGGGGGGGGTTGDDGGGGGGGGGGGGGGGGGGD",
    ),
    (#23
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                  GG                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  tD                  D",
        "D                  tD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "D                  DD                  D",
        "DTTTTTTTTTTTT      DD                  D",
        "DDDDDDDDDDDDD      DD                  D",
        "D                  DD                  D",
        "D                  DD               EE D",
        "D R                DD               EE D",
        "DGGGGGGGGGLLLLLLLLLDDGGGGGGGGGGGGGGGGGGD",
    ),
    (#24
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DR                                                                                                                                     D",
        "DG                                                                                                                                     D",
        "Dt                                                                                                                                     D",
        "Dt                                                                                                                                     D",
        "DG                                                                                                                                     D",
        "D                                                                      G                                                               D",
        "D                                                                      t                                                               D",
        "D                                                                      t                                                            EE D",
        "D                                                                      G                                                            EE D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "DT                                                                                                                                     D",
        "DG                                                                                                                                     D",
        "D                                                                      T                                                               D",
        "D                                                                      G                                                               D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "D                                                                                                                                      D",
        "DLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLGGD",
    ),
    (#25
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "D                                      D",
        "D                                      D",
        "D                   G                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                  BD                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "DB                  D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D                  D",
        "D                   D               EE D",
        "D R              B  D               EE D",
        "DGGGGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGD",
    ),
    (#26
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "DR   D                                  DEED",
        "DG   D                                  DEED",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                 B   D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D    D                                     D",
        "D                                          D",
        "D                                          D",
        "DLLLTTTLLLLLLLLLLLLLLLLLLLLLLTTLLLLLLLLLLLLD",
    ),
)

# test stage
    # (
    #     "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    #     "D                                      D",
    #     "DGG                                    D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                      D",
    #     "D                                EE    D",
    #     "D                                EE    D",
    #     "D                                      D",
    #     "D                                      DGGGGGG",
    #     "DGGGGGGGGGGGGGGG                             D",
    #     "DDDDDDDDDDDDDDDD                             t",
    #     "DDDDDDDDDDDDDDDD                             t",
    #     "DDDDDDDDDDDDDDDDLLLLLLLLLG      GTTG         D",
    #     "DDDDDDDDDDDDDDDDDDDDDDDDDD      DDDDGGGGGGGGGD",
    #     "D                                            D",
    #     "D                                            D",
    #     "D                                            D",
    #     "D                                            D",
    #     "D                     B                      D",
    #     "DGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGD",
    # ),