def level():
    A1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                 WWWW                  ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    ]
    B1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "             WWWWWW                    W",
        "             WWWWWW                    W",
        "        WWWWWWWWWWW                    W",
        "        WWWWWWWWWWW                    W",
        "WWWWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWW"
    ]

    B2 = [
        "WWWWWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWW",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                   WWWWWW              ",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                    WWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                     WWW",
        "                                       W",
        "                                       W",
        "WWWWWWWWWW                             W",
        "WWWWWWWWWW                             W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    A2 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                     WWWW              ",
        "W                     WWWW              ",
        "W                     WWWWWWWW          ",
        "W                     WWWWWWWW          ",
        "W                     WWWWWWWWWWWWWWWWWW",
        "W                     WWWWWWWWWWWWWWWWWW",
        "WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWWW",
    ]

    A3 = [
        "WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W               WWWWWW                 W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                           WWWWWW     W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    B3 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W           U                          W",
        "W                                      W",
        "W         WWWWW                        W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                  WWWWW               W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "          WWWWW                        W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C2 = [
        "WWWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWW",
        "      W                                W",
        "      W                                W",
        "      W           WWWWWW               W",
        "      W                                W",
        "W     W                                W",
        "W     W                                W",
        "W     W                                W",
        "W     W                                W",
        "W     W                                W",
        "W                        WWWW          W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W            WWWW                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                              WWWWWWWWW",
        "W                              WWWWWWWWW",
        "W                              WWWWWWWWW",
        "W                              WWWWWWWWW",
        "W                              WWWWWWWWW",
        "W                              WWWWWWWWW",
        "WWWWWWWWWWWWWWWWW       WWWWWWWWWWWWWWWW",
    ]

    D1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWW                                  W",
        "WWWWW                                  W",
        "WW                                      ",
        "WW                                      ",
        "WW                                      ",
        "WW                                      ",
        "WWWWWWWWWWWWWWWWWWW       WWWWWWWWWWWWWW",
    ]

    E1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                 WWWWWW",
        "W                                      W",
        "W                      WWWW            W",
        "W                                      W",
        "W            WWWW                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    D2 = [
        "WWWWWWWWWWWWWWWWWWW       WWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                  WWWWWWW             W",
        "W                                      W",
        "W                                      W",
        "W             WWWW                     W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                      WWWW            W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW",
    ]

    D3 = [
        "WWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                WWWWWW                W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                WWWWWW                W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                WWWWWWWW               W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C3 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                       ",
        "W   WWWWWWWWWWWWWWWWWWWWWW              ",
        "W                        W              ",
        "W                        W              ",
        "WWWWWWWWWWWWWWWW        WWWWWWWWWWWWWWWW",
    ]

    C4 = [
        "WWWWWWWWWWWWWWWW        WWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W              WWWWWWWWWW              W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W             WWWWWWWWWWWW             W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                   WWWWW",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    B4 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                 WWWWWWW                ",
        "                 WWWWWWW                ",
        "                 WWWWWWW                ",
        "                 WWWWWWW                ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    A4 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                U                      ",
        "W                                       ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    F1 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWW                  W               W",
        "W                      W               W",
        "W                      W               W",
        "W    WWW               W               W",
        "W                      W               W",
        "W                      W               W",
        "W                      W               W",
        "W       WWW            W               W",
        "W                      W               W",
        "W                      W               W",
        "W                      W               W",
        "W                      W               W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW      WWWWWW",
    ]

    F2 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW      WWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                           WWWWWW     W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                     WWWWWW           W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    E2 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                     W                W",
        "W                     W                W",
        "W                     W                W",
        "W      WWWWWWWWWWWWWWWW                W",
        "W                     W                 ",
        "W                     W                 ",
        "W                     W                 ",
        "W                     W                 ",
        "WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWWW",
    ]

    E3 = [
        "WWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W               WWWWWW                 W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                           WWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    F3 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWW                                 W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW      WWWWWW",
    ]

    F4 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWW      WWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                           WWWWWW     W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                  WWWWW",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "      0                             U  W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    E4 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                        ",
        "                                        ",
        "W                                       ",
        "W       F               F               ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    D4 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                  WWWWW",
        "W                                      W",
        "W                                      W",
    ]

    D5 = D6 = [
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
    ]

    D7 = [
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    E7 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                  S   W",
        "W       WWWWWWWW               WWWWWWWWW",
        "W       WWWWWWWW               WWWWWWWWW",
        "W       WWWWWWWW                       W",
        "        WWWWWWWW                        ",
        "        WWWWWWWW                        ",
        "        WWWWWWWW                        ",
        "        WWWWWWWW          F             ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    F7 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W  S                                S  W",
        "WWWW                                WWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W  S                                S  W",
        "WWWW                                WWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW      W",
    ]

    F8 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                WWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                WWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                               WWWWWWWW",
        "                                       W",
        "                                       W",
        "                  F                    W",
        "         WWWWWWWWWWWWWWWWWWW           W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW      W",
    ]

    E8 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W          B                B          W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    F9 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW      W",
        "                                       W",
        "                                       W",
        "                                 WWWWWWW",
        "                                       W",
        "WWWWWWWWW                      B       W",
        "W                                      W",
        "W            B                         W",
        "W                         WWWWW        W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWW                              W",
        "W                                      W",
        "W        B                             W",
        "W                                      W",
        "W                                 B    W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    E9 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                       ",
        "W                                       ",
        "W         B                             ",
        "W                                       ",
        "W                                 WWWWWW",
        "W                   WWWWWWWWWWWWWWW    W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W         F                            W",
        "WWWWWWWWWWWWWWWWWWWW             B     W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    D9 = [
        "W      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                 B                    W",
        "W                                      W",
        "WWWWW                                  W",
        "W                                      W",
        "W                                      W",
        "W                                   S  W",
        "W                                   WWWW",
        "W  S                                   W",
        "WWWW                                   W",
        "W                                      W",
        "W                                      W",
        "W                                  WWWWW",
        "W                                       ",
        "W                 B                     ",
        "W                                       ",
        "W S                                     ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    D8 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "                                       W",
        "                                       W",
        "              F                        W",
        "          WWWWWWWW                     W",
        "WWWWW                                  W",
        "W                                      W",
        "W                                      W",
        "W                        F             W",
        "W                    WWWWWWWW          W",
        "W                                      W",
        "W                                      W",
        "W   F                                  W",
        "WWWWWWWWW                              W",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W             F          F              ",
        "W      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C8 = [
        "W       WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                  WWWWW",
        "WWWWWWWWW                              W",
        "W                                      W",
        "W                                      W",
        "W                     L                W",
        "                   WWWWWWWWWWWWWWWWWWWWW",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWW                              W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C7 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "                                       W",
        "                                       W",
        "                                       W",
        "             F                         W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWW            W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                         F        S   W",
        "W            WWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W S                                    W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWW            W",
        "W                                      W",
        "W                                      W",
        "W                                 F    W",
        "W      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    B7 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "                   WW                   ",
        "                   WW                   ",
        "                   WW                   ",
        "                   WW                   ",
        "WWWWW              WW              WWWWW",
        "W                  WW                  W",
        "W                  WW                  W",
        "W                  WW                  W",
        "W       B          WW          B       W",
        "W                WWWWWW                W",
        "W                  WW                  W",
        "W                  WW                  W",
        "W                                      W",
        "W      F                               W",
        "WWWWWWWWWWWWWW            WWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    A7 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W            WWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W    F                                 W",
        "WWWWWWWWWWWWWWWWWWW                    W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                             F        W",
        "W                          WWWWWWW     W",
        "W                                      W",
        "W                                      W",
        "W      B                               W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWW",
    ]

    A8 = [
        "WWWWWWWWWWWWWWWWWWW      WWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W       S                              W",
        "W       WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W      S                               W",
        "WWWWWWWW                               W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                   S  W",
        "WWWWWWWWWWWWWWWWWWWW       WWWWWWWWWWWWW",
    ]

    A9 = [
        "WWWWWWWWWWWWWWWWWWWW       WWWWWWWWWWWWW",
        "W                              W       W",
        "W                              W       W",
        "W                              W       W",
        "W               WWWWWWWWWWWWWWWW       W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWW             W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                           L          W",
        "W             WWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                 W                    W",
        "W                 W                    W",
        "W                 W                    W",
        "W                           U          W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    B8 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                            B         W",
        "W                                      W",
        "W             W                        W",
        "W             W                        W",
        "W             W                        W",
        "W             W                        W",
        "WWWWW         W                        W",
        "W             W                         ",
        "W             WWWWW                     ",
        "W             W                         ",
        "W      B      W                         ",
        "W             WWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W             W                        W",
        "W         WWWWW                        W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWW    WWWWWWWWW",
    ]

    B9 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWW    WWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                 WWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWW                W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W             WWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    C9 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                  1                   W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    W",
    ]

    C10 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                 WWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W              WWWWW                   W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                       WWWWW          W",
        "W                                      W",
    ]

    C11 = [
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W             WWWWW                    W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                      WWWWW           W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W            WWWWW                     W",
        "W                                      W",
        "W                                      W",
    ]

    C12 = [
        "W                                      W",
        "W                                      W",
        "W                      WWWWW           W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W          WWWWW                       W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                       ",
        "W                  WWWWW                ",
        "W                                       ",
        "W                                       ",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    D12 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                       ",
        "W                                    WWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                             WWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWW                             W",
        "W                                      W",
        "W                                      W",
        "                                       W",
        "                                       W",
        "                                       W",
        "            I                 I        W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    E12 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "                                       W",
        "                                       W",
        "                                       W",
        "                                       W",
        "WWW                                    W",
        "W                                      W",
        "W                                      W",
        "W        WWWWWW                        W",
        "W                          C           W",
        "W                                       ",
        "W                                       ",
        "W            C                          ",
        "W                    WWWWWW             ",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW     WWWWW",
    ]

    E13 = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW     WWWWW",
        "W                                      W",
        "W                                      W",
        "W                            WWWWWWW   W",
        "W                                      W",
        "W P                                    W",
        "WWWW                 WWWW              W",
        "W                                      W",
        "W                                      W",
        "W P                                    W",
        "WWWW                                 P W",
        "W                    WWWW            WWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    x = [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

    OO = [
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
    ]

    # world is a list of the levels.
    # the world holds each level the same way a level holds each platform.
    return [
        [A1, B1, C1,  D1,  E1,  F1],
        [A2, B2, C2,  D2,  E2,  F2],
        [A3, B3, C3,  D3,  E3,  F3],
        [A4, B4, C4,  D4,  E4,  F4],
        [OO, OO, OO,  D5,  OO,  OO],
        [OO, OO, OO,  D6,  OO,  OO],
        [A7, B7, C7,  D7,  E7,  F7],
        [A8, B8, C8,  D8,  E8,  F8],
        [A9, B9, C9,  D9,  E9,  F9],
        [OO, OO, C10, OO,  OO,  OO],
        [OO, OO, C11, OO,  OO,  OO],
        [OO, OO, C12, D12, E12, OO],
        [OO, OO, OO,  OO,  E13, OO]
    ]

# Current unique branch-ends: D12 (going to E12)
